### ISSUE TITLE
Backend is OOMKilled every day

### ISSUE THREAD

**Issue by dlebrero** [akvo/akvo-flow-api#136]
Mem limit too low

**Comment by iperdomo** [comment]
We still have the issue
```
  containerStatuses:
  - containerID: docker://468c57e33a5eb042cbaa43b04b3f1f1c3846536363e45e2066f27e399cdf0278
    image: akvo/flow-api-backend:c460cc687ea8465e2b0c7f39fd8159d1664d37ba
    imageID: docker-pullable://akvo/flow-api-backend@sha256:5184b569a4d513aee538f54c2882c9cc3bf25449c3cdbe6cc9a3f8f464e14b78
    lastState:
      terminated:
        containerID: docker://0d65f8b799acd96a8965f26e99ffa2614434800bd7384d59f1926928dbe13c5b
        exitCode: 137
        finishedAt: 2018-08-13T10:52:56Z
        reason: Error
        startedAt: 2018-08-13T01:06:32Z
    name: flow-api-backend
    ready: true
    restartCount: 9
    state:
      running:
        startedAt: 2018-08-13T10:52:58Z
```
